module Ftpd

  # All errors (purposefully) generated by this library driver from
  # this class.

  class FtpServerError < StandardError ; end

  # Any error that send a reply to the client raises a CommandError.
  # The message is the text to send (e.g. "501 Syntax error").  This
  # is typically not raised directly, but using the Error mixin.

  class CommandError < FtpServerError ; end

  # A permanent file system error.  Deprecated; use
  # PermanentFileSystemError instead.

  class FileSystemError < FtpServerError ; end

  # A permanent file system error.  The file isn't there, etc.

  class PermanentFileSystemError < FtpServerError ; end

  # A transient file system error.  The file is busy, etc.

  class TransientFileSystemError < FtpServerError ; end

end
