module Ftpd

  # All errors (purposefully) generated by this library driver from
  # this class.

  class FtpServerError < StandardError ; end

  # Any error that send a reply to the client raises a CommandError.
  # The message is the text to send (e.g. "501 Syntax error").  This
  # is typically not raised directly, but using the Error mixin.

  class CommandError < FtpServerError ; end

  # Any errors raised by a file system driver are (or are derived
  # from) this class.  See the mixin TranslateExceptions for an easy
  # way to generate FileSystemError exceptions from other types of
  # exceptions.

  class FileSystemError < FtpServerError ; end

end
